language: go

os:
  - osx
  - windows
  - linux

go:
  - 1.15.x
  - 1.16.x

go_import_path: github.com/thinkgos/TODO_ADD_PACKAGENAME

script:
  - go get -v ./...
  - go test -v -benchmem -test.bench=".*" -coverprofile=coverage.txt -covermode=atomic  ./...

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then curl -s https://codecov.io/bash >
    .codecov && chmod +x .codecov && ./.codecov; else bash <(curl -s https://codecov.io/bash);
    fi

env:
  global:
    - GO111MODULE=on
